package controllers;

import javafx.fxml.FXML;
import javafx.scene.control.TextField;
import models.Activites;
import models.Tour;
import services.ActivitesService;

import java.sql.SQLException;

public class AddActivityController {

    @FXML
    private TextField nameField;

    @FXML
    private TextField startDateField;

    @FXML
    private TextField endDateField;

    @FXML
    private TextField locationField;

    @FXML
    private TextField photoField;

    @FXML
    private TextField descriptionField;

    private Tour currentTour;
    private final ActivitesService activitesService = new ActivitesService();

    public void setCurrentTour(Tour tour) {
        this.currentTour = tour;
    }

    @FXML
    private void handleAddActivity() {
        try {
            Activites activity = new Activites(
                    0, // ID will be auto-generated by the database
                    nameField.getText(),
                    startDateField.getText(),
                    endDateField.getText(),
                    locationField.getText(),
                    photoField.getText(),
                    descriptionField.getText(),
                    currentTour
            );

            boolean success = activitesService.ajouter(activity);
            if (success) {
                nameField.getScene().getWindow().hide(); // Close the window
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}